services:
  app:
    build: .
    container_name: inventorypy
    environment:
      - DB_HOST=mongodb
      - DB_PORT=27017
    depends_on:
      - mongodb

  mongodb:
    image: "mongo:latest"
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
